---

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - https://raw.githubusercontent.com/decidim/decidim/0.14-stable/.rubocop.yml
  - https://raw.githubusercontent.com/decidim/decidim/0.14-stable/.rubocop_rails.yml

AllCops:
  Exclude:
    - db/schema.rb
    - "**/spec/decidim_dummy_app/**/*"

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile
    - Rakefile

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/*"

RSpec/ImplicitSubject:
  Enabled: false
