# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  analytics:
    matomo_server: <%= ENV["MATOMO_SERVER"] %>
    matomo_site_id: <%= ENV["MATOMO_SITE_ID"] %>
  airbrake:
    api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
    host: <%= ENV["AIRBRAKE_HOST"] %>
    project_id: <%= ENV["AIRBRAKE_PROJECT_ID"] %>
  geocoder:
    here_app_id: <%= ENV["GEOCODER_LOOKUP_APP_ID"] %>
    here_app_code: <%= ENV["GEOCODER_LOOKUP_APP_CODE"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
    twitter:
      enabled: false
    google_oauth2:
      enabled: false
    participa:
      enabled: <%= ENV["OMNIAUTH_PARTICIPA_OPENID"] %>
      openid_identifier: <%= ENV["OMNIAUTH_PARTICIPA_OPENID_IDENTIFIER"] %>
      icon_path: participa.svg

development:
  <<: *default
  secret_key_base: 9cb6e6106aeae7ba1224be8103dabfdb098ef2e18d751258efa34487caa5d249246419431ce6dcc8db1393073a68270c9110f3fc40dc41cd80d4b2309cb1ae35
  mail_from: info@programas-dev

test:
  <<: *default
  secret_key_base: 65ee8b09cc9c88904f27114d178089c0559a1173538bf7e0305cf00d07558329f45d3e60e36e2aedfdf020b067480c759b7279e45f49021616caf862d6787415
  mail_from: info@programas-dev
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail_from: <%= ENV["MAIL_FROM"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_starttls_auto: true
  smtp_authentication: "plain"
